### ISSUE TITLE
experiments/DTD/ResNeSt-0.001-0.4-DTDColorPatches/saved_model

### ISSUE THREAD

**Issue by LRHstudy** [FabianGroeger96/semantic-segmentation-dtd#3]
can't find the saved_model when i run 'python -m src.inference'

**Comment by FabianGroeger96** [comment]
This was fixed in the latest commit: [2aaed00](https://github.com/FabianGroeger96/semantic-segmentation-dtd/commit/2aaed006e207157084d7fe5709a9c162515d7a4d)

If you want/need to change the model to use during inference you can change the model path within the `inference` script.
